[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
maplit = "1.0.2"
phf = { version = "0.11.1", features = ["macros"] }
stopwatch = "0.0.7"

[dev-dependencies]
test-case = "2.2.2"
